### ISSUE TITLE
Public IIS

### ISSUE THREAD

**Issue by henriqueandradesilva** [thewebchameleon/TemplateV2.Razor#2]
Hello how are you? when I publish to IIS
works perfectly, but does not enter the panel screen, I tested it by validating the login with invalid data that normally validates, but does not enter the panel, could you help me?

**Comment by thewebchameleon** [comment]
Hi there, you may be experiencing this due to the site not having an HTTPS binding in IIS, are you accessing it via HTTP?

**Comment by henriqueandradesilva** [comment]
Exactly, just for testing I am using via http, is there anything I can do to use only via http? for now

**Comment by thewebchameleon** [comment]
You'll want to comment out this line in `Startup.cs`:

`app.UseHttpsRedirection();`
