### ISSUE TITLE
Routing error after bad login

### ISSUE THREAD

**Issue by martinsustek** [thewebchameleon/TemplateV2.Razor#4]
After unsuccessful login the form that is generated has wrong ReturnUrl.
An error occurs after second login attempt.

**Comment by thewebchameleon** [comment]
@martinsustek, could you provide steps to reproduce this bug?

I have tried the following:
1. Access [https://templatev2-razor.azurewebsites.net/Admin/Configuration](https://templatev2-razor.azurewebsites.net/Admin/Configuration) , page gets redirected to the login page
2. Type in the incorrect password for an account and click 'Login' (U: admin; P: 111)
3. Type in the correct password for an account and click 'Login' (U: admin; P: 123456)
4. Page is redirected to url in the query string variable ReturnUrl (admin configuration page)

**Comment by martinsustek** [comment]
Ok, for some reason, it works on your azure hosting, but not on my development environment.

1. I open https://localhost:5001/
2. it redirects me automatically to https://localhost:5001/Account/Login?ReturnUrl=%2F
3. I enter wrong password (admin/111)
4. It shows https://localhost:5001/Account/Login?returnurl=%2F (notify lowercase - returnurl, not ReturnUrl) with error "Username or password is incorrect"
5. I enter correct password (admin/123456)
6. It shows https://localhost:5001/Account/Login (no return url at all) with error "The returnUrl field is required."

However, on your hosting it also uses lowercase letters in step 4, but it works and url gets transfered to step 6. There is probably something with server configuration. I use .NET SDK 5.0.201 and run from VSCode.

**Comment by thewebchameleon** [comment]
On step 1, did you mean you open [https://localhost:5001/Admin/Configuration](https://localhost:5001/Admin/Configuration)?

It should redirect you to https://localhost:5001/Account/Login?ReturnUrl=%2FAdmin%2FConfiguration

Case sensitivity shouldn't be an issue

**Comment by martinsustek** [comment]
Hello,
I've tried it using link you've provided, and the behaviour is the same. First is ReturnUrl, then returnurl. On my local machine it's case sensive, on your server case insensitive.

https://user-images.githubusercontent.com/3765387/115459817-c526a300-a227-11eb-99b4-feefbf55d7b7.mp4

**Comment by thewebchameleon** [comment]
Have you tried cloning a fresh copy of the repo and trying again?

I have tried on my dev machine but am unable to reproduce the same behaviour. It works for me. (Visual Studio).

Alternatively, there might be a fix [here](https://github.com/dotnet/aspnetcore/issues/22656#issuecomment-640650945)?

**Comment by martinsustek** [comment]
It probably works, as you've merged my pull request, haven't you?
https://github.com/thewebchameleon/TemplateV2.Razor/commit/a91abfb87eaa7496279fe7afdb8e069cdfd5cca7
I was trying it on my old checkout, on the latest, it works.
