### ISSUE TITLE
Postgresql Support?

### ISSUE THREAD

**Issue by vector-man** [thewebchameleon/TemplateV2.Razor#8]
Your project is awesome! I haven't reviewed the code extensively, but would it be much work to get this running on a Postgresql database?

**Comment by thewebchameleon** [comment]
I have not tried this project with PostgreSQL but I don't see much work being done, you would need to update the schema for  stored procedures and tables for any syntax differences. 

Only caveat I can think of is that the database project probably won't be compatible.
